### PR TITLE
give tips for timing; closes #103

### LINKED ISSUE #103: Lesson does not fit into 1.5 hours
Either remove material or make more clear what should be jumped over and left for later reading.

### PR DESCRIPTION
**Pull request by bast**
I think it's better if we have more material but only select what to teach rather than cutting the material down further.

### CODE REVIEW

**Comment by bast** [comment]
Good idea. I will add that and I will merge then.

**Comment by annefou** [comment]
I added some information in the intructor guide. Some exercises can be shorten and the episode on Github webpage can also be skipped if needed.

**Comment by wikfeldt** [comment]
now this PR conflicts. Are the changes here now redundant after merging https://github.com/coderefinery/documentation/pull/127 ?

**Comment by annefou** [comment]
I re-arranged it so we have all inputs from everybody.

**Comment by annefou** [comment]
Shall we merge it now?

**Pull request merged**
