### PR TITLE
svg update according to annajiat suggestions, main naming and coloring

### PR DESCRIPTION
**Pull request by samumantha**
Follow up PR to provide updated svg file of the gh pages illustration as suggested by @annajiat 
Further updates:
- master -> main branch naming
- coloring (please suggest better color palette for color blind friendlyness)

### CODE REVIEW

**Comment by bast** [comment]
Why is the jpg conflicting? Do we need the jpg having the svg?

**Comment by samumantha** [comment]
The jpg does not exist anymore in my fork. Don't know why that is a conflict.

**Comment by bast** [comment]
Maybe because it got modified in the other PR and removed in this PR and this PR branched off from an earlier situation?

**Comment by samumantha** [comment]
yes, that was it, I forked the repository much earlier and it did not contain some earlier changes as well. Now it should be fine? Please review and merge :)

**Comment by samumantha** [comment]
Updated colors according to suggestions from link in issue #161 to red, orange and blue.

Please review and merge!

**Comment by samumantha** [comment]
The svg is now moved onto A4 page (it was only partly on before), to be used as is without the need to generate jpg.
Please review in context

**Comment by samumantha** [comment]
updated and ready for merge (from my side)

**Pull request merged**
