### PR TITLE
GitHub pages

### PR DESCRIPTION
**Pull request by rantahar**
Switch from Read the Docs to Github Actions and Pages

### CODE REVIEW

**Review by bast — APPROVED** [review]
Looks good! Can we also say somewhere that a similar approach is possible for GitLab pages? But can also be done as follow up.

**Comment by bast** [comment]
We also need to adapt https://coderefinery.org/installation/removing-accounts/#read-the-docs - can you please send a PR also towards there?

**Comment by bast** [comment]
> We also need to adapt https://coderefinery.org/installation/removing-accounts/#read-the-docs - can you please send a PR also towards there?

I will remove it from install instructions.

**Comment by rantahar** [comment]
I haven't done this with GitLab, but it seems very similar. We should add tabs with GitLab instructions.

For now, I'm just adding a comment.

**Comment by rantahar** [comment]
@bast, ready to merge?

**Comment by bast** [comment]
Thanks!

**Pull request merged**
