### PR TITLE
Added clarity to the illustration and the text

### PR DESCRIPTION
**Pull request by annajiat**
1) Emphasized that the instructions are to be followed directly from the github pages and merged the relevant lines from the end of the exercise.

2) Resequenced the phrase to wait few minutes first and then try to see the changes.

3) Modified the illustration to add clarity and to make the URLs consistent. 
3.1) URLs were inconsistent
Personal homepage, https://myuser.github.io did not have any trailing slash but all other github pages and other URL had trailing slash.
Made everything consistent by removing all trailing slashes from all URLs.

3.2) Added clarity about branches and distinction between github and gh-pages URLs
Beginners had difficulties in the ongoing coderefinery workshop that gh-pages referred to a branch and what the 2nd URL io means.
Added following labels for all respective URLs
(in the master branch)
(generated URL fo the site)
(in the gh-pages branch)
 
3.3) Project website organizational and personal URLs were too close compared to the distance between github and io pages. Increased the distance and moved last two URLs further down.

### CODE REVIEW

**Comment by annajiat** [comment]
For convenience in comparison, please find the illustrations below: 

**New illustration:**
gh-pagesV2


**Old Illustration:**
gh-pages

**Review by wikfeldt — APPROVED** [review]
i like these changes! make it significantly clearer i think. Not merging yet because maybe we should actually replace the figure instead of adding V2

**Comment by annajiat** [comment]
1. deleted gh-pages.jpg
2. updated reference of gh-pagesV2.jpg to gh-pages.jpg  
3. added gh-pages.jpg which was renamed from gh-pagesV2.jpg

**Comment by bast** [comment]
Were the changes done in the svg file? The svg file is the source of the jpg file. I am asking this because I don't see svg in this pull request.

**Comment by annajiat** [comment]
Changes where done in the JPG file directly.

**Comment by bast** [comment]
It would be better I think if we change the svg and generate jpg from it. But I like the changes and don't want to put this extra work on you and I can also take care of this and we can leave the PR open until then.

**Comment by bast** [comment]
This is not forgotten and it is appreciated. I will soon come back to processing this.

**Comment by samumantha** [comment]
updated the svg to this (master -> main; color update, otherwise followed @annajiat suggestions): 
image
If this is approved, how to best add the new svg to this PR?  
And is the jpg automatically created from it or do I need to upload it separately?

**Comment by annajiat** [comment]
Thank you so much @samumantha 
It looks great!
Would you like to crop the extra blank spaces on all four sides?
I think JPG needs to be uploaded separately.

**Comment by samumantha** [comment]
Ah yes, this was just a quick screenshot, the svg file itself will be  cut with the textbox

**Comment by bast** [comment]
I think we might not need the jpg. The page can deal with svg as far as I know.

**Comment by bast** [comment]
About how to add it: I suggest we merge and send the svg as follow-up PR.

**Pull request merged**
