### PR TITLE
Seperate rtd gitlab episode

### PR DESCRIPTION
**Pull request by svenvanderburg**
We're teaching this lesson using gitlab and we use the rtd lesson as a standalone exercise. I adapted it so the instructions match gitlab better. You might want to use this in the official lesson.

TODO: Please note that instead of using the github template example project, instructions mention to fork the example project from https://gitlab.com/svenvanderburg/word-count on my own account's namespace. I think you should create this on a gitlablcom/code-refinery namespace.

### CODE REVIEW

**Comment by bast** [comment]
Thanks a lot Sven! This is great. What we can then do post-merge is to combine these into one episode but then learners can select with tabs whether they follow this on GitHub or GitLab.

**Comment by svenvanderburg** [comment]
@bast that sounds nice!

**Comment by bast** [comment]
Sorry that this is open for quite a bit. It is not forgotten. I will soon merge it but wanted to make it properly and also make sure I move the template repo and that I add some acknowledgement.

**Comment by bast** [comment]
Thanks again! Following up with two issues in #162 and #163.

**Pull request merged**
