### PR TITLE
fix path to solve issue #91

### PR DESCRIPTION
**Pull request by annefou**
This should fix issue #91 and issue #49

### CODE REVIEW

**Comment by annefou** [comment]
It should fix box issues #91 and #49 (I did not realized I was not using branches...).

**Comment by bast** [comment]
The exercise that is now added used to be there. When I look at the diff it looks like it has been added from scratch so my question is - where has it been removed?

**Comment by wikfeldt** [comment]
it's the exercise that used to be in the readthedocs.io/word-count example documentation, right?

**Comment by annefou** [comment]
Yes it is related to the issue #49 where it was suggested to move the exercises from here:
https://github.com/coderefinery/word-count/blob/master/doc/exercises.rst

to here:
https://github.com/coderefinery/documentation/blob/gh-pages/_episodes/04-sphinx-rtd.md

I did not removed the exercise from https://github.com/coderefinery/word-count yet. I'll do it once we solve issue#49 first.

**Comment by bast** [comment]
Ah good - sorry, I should have checked the issue.

**Pull request merged**
