### PR TITLE
Change focus of lesson to in-code documentation and README files

### PR DESCRIPTION
**Pull request by svenvanderburg**
Changes lesson to focus more on best practices for in-code documentation and README files. See https://escience-academy.github.io/coderefinery-documentation/ 

The new structure is as follows:
* Episode 1: Still motivation and wishlist, but shortened a bit, to quickly converge on a wishlist for good documentation.
* Episode 2: In-code documentation. Teaches about when and how to use comments, and about writing good docstrings.
* Episode 3: Readme files. Teaches what should go in a good readme file
* Episode 4: Demo of sphinx and readthedocs. This replaces the old episodes 3 & 4 that let students setup sphinx and readthedocs with just a quick demo of what you can accomplish with sphinx and readthedocs. The rationale being that for 70% of the students that attend coderefinery workshops learning how to do this is overkill, they will not use sphinx in practice.
* Episode 5: Unaltered github pages episode
* Episode 6: Unaltered recap episode

* Removed episode 2: tools, because students did not want to learn about all the different methods out there. They just want to learn a good approach that works well, and they will learn about other tools (i.e. latex documentation for example) when they encounter it in the wild.

Additional improvements:
* Add a Makefile
* Update gitignore

Depends on https://github.com/escience-academy/coderefinery-documentation-example-project which would have to be moved to coderefinery.

TODO:
* Decide on how to use this
* Fix references to old repo
* Adjust timings

### CODE REVIEW

**Comment by bast** [comment]
Thanks for this! Few quick comments but I will read more and think more and also happy to video talk:
- I agree that simpler and more pragmatic and refocus is good here
- I would not remove the tools section but better indicate to future instructors that they can choose to skip it
- At this stage I am worried about conflicts since we plan to migrate the lesson to Sphinx for our workshop which is one month from now but let me review first and perhaps we can split this PR into smaller chunks to make this easier

**Comment by svenvanderburg** [comment]
@bast 
* Agreed to not remove the tools section

Let me know what your thoughts are after your review,  if necessary I am also happy to video talk!

**Comment by bast** [comment]
I am now working on getting #167 in which will create some conflicts here but let's not close it. I will then help to move changes from here to the new format.

**Comment by bast** [comment]
I will now change default branch which I think will automatically close this PR. But we will follow up on this as discussed in #166.

**Pull request closed without merging**
