### PR TITLE
fix issue #80 added task style for exercises

### PR DESCRIPTION
**Pull request by annefou**

### CODE REVIEW

**Comment by wikfeldt** [comment]
thanks for the improvement, but does this PR contain some commits that have already been merged? like this one: ed46a0e194afb1552723e1166f18b66ca37b25c2

**Comment by annefou** [comment]
Yes, that's mostly because I forgot to update this exercice last time so I thought it would be nice to have it too.

**Comment by wikfeldt** [comment]
so is everything as it should? i just became unsure if some changes had been mixed and some cleanup was necessary

**Comment by annefou** [comment]
Yes. I hope so. My idea was to close the issue #80

**Pull request merged**
